### ISSUE TITLE
AttributeError: type object 'OFASys' has no attribute 'from_pretrain'

### ISSUE THREAD

**Issue by lllxf** [OFA-Sys/OFASys#13]
![image](https://github.com/OFA-Sys/OFASys/assets/116485306/40fc4b4e-0a6a-4774-a287-0461e71c4268)

**Comment by johnwick123f** [comment]
@lllxf I believe the problem is you did
OFASys.from_pretrain

while your supposed to do
OFASys.from_pretrained
