### ISSUE TITLE
How to train the Generalist Model in your paper?

### ISSUE THREAD

**Issue by ilovecv** [OFA-Sys/OFASys#3]
Thank you very much for sharing the awesome work!

Could you please share more information on how to train the Generalist Model in your paper? Like how to construct the datasets for different tasks. 

BTW, when I run the inference code, it had the error: No module named 'datasets.utils'
<img width="450" alt="Screenshot 2023-01-05 at 7 39 36 PM" src="https://user-images.githubusercontent.com/11083384/210925358-ce9d32f3-bbfc-4abc-92cf-2c9561f9d6e1.png">

**Comment by ilovecv** [comment]
thanks!

**Comment by tankche1** [comment]
> Thank you for your attention. We are sorting out all scripts and data to train the Generalist Model and expect to update it in the next patch **next week**. We will also add documentation about more launching detail of reproducing.
> 
> The `ModuleNotFoundError` may be caused by not installing all requirements correctly. You can be fixed it by `pip install -r requirements.txt` or `pip install datasets`. The requirements file is in [here](https://github.com/OFA-Sys/OFASys/blob/main/requirements.txt#L14).

Hi, I wonder when you will release the script to train the model in your paper?
